<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Melanin.Application\Melanin.Application.csproj" />
    <ProjectReference Include="..\Melanin.Domain\Melanin.Domain.csproj" />
    <ProjectReference Include="..\Melanin.Infrastructure.Mailer\Melanin.Infrastructure.Mailer.csproj" />
    <ProjectReference Include="..\Melanin.Infrastructure.Sqlite\Melanin.Infrastructure.Database.Sqlite.csproj" />
    <ProjectReference Include="..\Melanin.Infrastructure.Stripe\Melanin.Infrastructure.Stripe.csproj" />
    <ProjectReference Include="..\Melanin.Infrastructure\Melanin.Infrastructure.Database.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ExceptionHandlers\" />
  </ItemGroup>

</Project>
